<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6lgNqnL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6lgNqnL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6lgNqnL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6lgNqnL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6lgNqnL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6lgNqnL',
    'container.build_id' => '203a6251',
    'container.build_time' => 1581536629,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6lgNqnL');
